apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blue-ingress 
  namespace: secure
spec:
  podSelector:
    matchLabels:
      run: blue
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: red
    ports:
    - protocol: TCP
      port: 80


