apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: red-ingress
  namespace: secure
spec:
  podSelector:
    matchLabels:
      run: red
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: subject
      podSelector:
        matchLabels:
          run: math
            
    - podSelector:
        matchLabels:
          run: orange
    ports:
    - protocol: TCP
      port: 80
