apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: cm
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: cm
data:
  log_level: INFO

